[build]
target = "x86_64-pc-windows-gnu"
# somehow only works on my steamos using mvsc, but on windows it works both ways
# on linux, it seems Nexus only recognizes the dll built with msvc
# target = "x86_64-pc-windows-msvc"